version: 0.2

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - python3 test_hello.py
  post_build:
    commands:
      - echo Build completed on `date`